# Generated by Django 5.1.5 on 2025-01-31 16:43

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_telegram_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="client",
        ),
        migrations.AddField(
            model_name="user",
            name="date_added",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_username",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="unique_user_id",
            field=models.CharField(
                default=uuid.uuid4, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
