- hosts: back_server  # Заменить на имя группы хостов (из inventory.ini)
  tasks:
    - name: Clone the repository
      git:
        repo: 'https://github.com/exchange-web/exchange-api'  # Заменить на URL твоего репозитория
        dest: /var/back/app  # Заменить на путь, куда клонировать репозиторий
        version: main  # Заменить на нужную ветку

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Get latest release of Docker Compose
      uri:
        url: "{{ item.url }}"
        method: GET
        return_content: true
      register: docker_compose_release
      loop: "{{ lookup('url', 'https://api.github.com/repos/docker/compose/releases/latest').json | json_query('assets[]') }}"
    
    - name: Install Docker Compose
      get_url:
        url: "{{ item.browser_download_url }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'
      loop: "{{ docker_compose_release.results[0].content.json | json_query('assets[]') }}"

    - name: Pull Docker images
      command: docker-compose pull
      args:
        chdir: /var/back/app  # Заменить на путь к папке с docker-compose.yml

    - name: Restart containers
      command: docker-compose up -d
      args:
        chdir: /var/back/app  # Заменить на путь к папке с docker-compose.yml


