- hosts: back_server  # Заменить на имя группы хостов (из inventory.ini)
  tasks:
    - name: Clone the repository
      git:
        repo: 'https://github.com/exchange-web/exchange-api'  # Заменить на URL твоего репозитория
        dest: /var/back/app  # Заменить на путь, куда клонировать репозиторий
        version: main  # Заменить на нужную ветку

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.32.4/docker-compose-darwin-aarch64"
        dest: /usr/local/bin/docker-compose
        mode: '0777'
      executable: true

    - name: Pull Docker images
      command: docker-compose pull
      args:
        chdir: /var/back/app  # Заменить на путь к папке с docker-compose.yml

    - name: Restart containers
      command: docker-compose up -d
      args:
        chdir: /var/back/app  # Заменить на путь к папке с docker-compose.yml


