version: '3.4'

volumes:
  postgres:

services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'exchange'
      POSTGRES_PASSWORD: '11111'
      POSTGRES_DB: 'exchange'
    volumes:
      - postgres:/var/lib/postgresql/data
    
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: exchange_local_web
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - 8000:8000