# Generated by Django 5.1.5 on 2025-01-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_entries", "0002_alter_dataentry_cross_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dataentry",
            name="date",
        ),
        migrations.AddField(
            model_name="dataentry",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="dataentry",
            name="date_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
