# Generated by Django 5.1.5 on 2025-01-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_entries", "0003_remove_dataentry_date_dataentry_date_created_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dataentry",
            old_name="amount",
            new_name="amount_in",
        ),
        migrations.AddField(
            model_name="dataentry",
            name="amount_out",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
